spring:
  output:
    ansi:
      enabled: always
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    name: todo
    url: jdbc:h2:~/todo
    driver-class-name: org.h2.Driver
  mustache:
    cache: false
    charset: UTF-8
    check-template-location: true
    content-type: text/html; charset=utf-8
    enabled: true
    prefix: classpath:/templates/
    suffix: .html
  h2:
    console:
      enabled: true
      path: /h2-console
